parameters:
#    kicker_table.example.class: HH\KickerTableBundle\Example

services:
#    kicker_table.example:
#        class: %kicker_table.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    kicker_table.parse_request_data_listener:
        class: HH\KickerTableBundle\EventListener\SoccerMatchListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: api.post_request_terminate, method: onTerminate }

    kicker_table.soccer_match_service:
        class: HH\KickerTableBundle\Service\SoccerMatchService
        arguments: [ "@doctrine.orm.entity_manager" ]