parameters:
#    kicker_table.example.class: HH\KickerTableBundle\Example

services:
#    kicker_table.example:
#        class: %kicker_table.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    kicker_table.parse_request_data_listener:
        class: HH\KickerTableBundle\EventListener\KickerTableListener
        arguments: [ @kicker_table.kicker_table_service ]
        tags:
            - { name: kernel.event_listener, event: api.new_device_message_appear, method: processMessage }

    kicker_table.kicker_table_service:
        class: HH\KickerTableBundle\Service\KickerTableService
        arguments: [ "@doctrine.orm.entity_manager" ]
