parameters:
    api.post_request_terminate.class: HH\ApiBundle\EventListener\PostRequestTerminate

services:
    api.post_request_terminate:
        class: %api.post_request_terminate.class%
        calls:
            - [ setDispatcher, [@event_dispatcher] ]
            - [ setMessageManager, [@api.message_manager]]
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate }

    api.message_manager:
        class: HH\ApiBundle\Service\MessageManager
        arguments:
            - @doctrine
