parameters:
#    api.example.class: HH\ApiBundle\Example

services:
#    api.example:
#        class: %api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    api.events_log_service:
        class: HH\ApiBundle\Service\EventsLogService
        arguments: [ "@doctrine.orm.entity_manager" ]

    api.request_manager:
        class: HH\ApiBundle\Service\RequestManager
        arguments: [ "@doctrine.orm.entity_manager" ]
        calls:
          - [setDispatcher, [@event_dispatcher]]
