parameters:
#    soccer_match.example.class: HH\SoccerMatchBundle\Example

services:
#    soccer_match.example:
#        class: %soccer_match.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    hh_soccer_match.parse_request_data_listener:
        class: HH\SoccerMatchBundle\EventListener\SoccerMatchListener
        arguments: [ "@service_container" ]
        tags:
          - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate }

    hh_soccer_match.soccer_match_service:
        class: HH\SoccerMatchBundle\Service\SoccerMatchService
        arguments: [ "@doctrine.orm.entity_manager" ]