HH\IceCreamBundle\Entity\IceCream:
    type: entity
    table: ice_cream
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: userId
        deviceid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: deviceId
        amount:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
