HH\ApiBundle\Entity\EventsLog:
    type: entity
    table: events_log
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        deviceid:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: deviceId
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
        type:
            type: string
            nullable: false
            length: 16
            fixed: false
            comment: ''
        devicetime:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: deviceTime
        data:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        processed:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
